# Generated by Django 2.0.4 on 2018-11-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20181111_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(default='poll_pics/empty.png', upload_to='poll_pics'),
        ),
    ]
